import { assistantFont } from '@/app/font';
import Header from '@/components/Header';
import type { Metadata } from 'next';
import { ReactNode } from 'react';
import './globals.css';
import { Providers } from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <main className={assistantFont.className}>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
